"""Qwen3 architecture builder.

Mirrors the layer layout used by ``Applications/CausalLM/models/qwen3``:

  input -> embedding0
        -> [for each i in [0, num_hidden_layers)]:
              attention_norm (rms_norm)
              wq, wk, wv     (fully_connected, no bias)
              q_norm, k_norm (reshaped_rms_norm, per-head)
              attention      (mha_core, GQA + RoPE)
              attention_out  (fully_connected, no bias)
              residual_attn  (addition with block input)
              ffn_norm       (rms_norm)
              ffn_up, ffn_gate (fully_connected)
              ffn_swiglu     (swiglu)
              ffn_down       (fully_connected)
              residual_ffn   (addition with post-attention residual)
        -> output_norm (rms_norm)
        -> lm_head (tie_word_embeddings or fully_connected)

Layer names match the existing C++ implementation so weight files produced by
either path are interchangeable.
"""

from __future__ import annotations

from . import register
from ..ini import IniSection
from ..weights import WeightBinding
from .base import ArchitectureBuilder


# Default RMSNorm epsilon if the HF config omits it (Qwen3 uses 1e-6).
_DEFAULT_RMS_EPS = 1.0e-6
# Default RoPE base frequency for Qwen3.
_DEFAULT_ROPE_THETA = 1_000_000


class Qwen3Builder(ArchitectureBuilder):
    model_type = "qwen3"

    # ----- INI emission ----------------------------------------------------
    def build_sections(self) -> list[IniSection]:
        cfg = self.cfg
        num_layers = int(self._require("num_hidden_layers"))
        hidden_size = int(self._require("hidden_size"))
        intermediate = int(self._require("intermediate_size"))
        n_heads = int(self._require("num_attention_heads"))
        n_kv = int(cfg.get("num_key_value_heads", n_heads))
        head_dim = int(cfg.get("head_dim", hidden_size // n_heads))
        vocab = int(self._require("vocab_size"))
        rope_theta = int(cfg.get("rope_theta", _DEFAULT_ROPE_THETA))
        max_pos = int(cfg.get("max_position_embeddings", self.ctx.max_seq_len))
        rms_eps = float(cfg.get("rms_norm_eps", _DEFAULT_RMS_EPS))
        tie = bool(cfg.get("tie_word_embeddings", False))

        sections: list[IniSection] = []

        # [Model]: minimal — runtime overrides batch_size and tensor type via
        # setProperty before loadFromConfig, but iniparser still requires the
        # section to be present.
        m = IniSection(
            "Model",
            comment=(
                f"Auto-generated by nntr_causal_lm_converter\n"
                f"architecture: qwen3\n"
                f"layers: {num_layers}, hidden: {hidden_size}, "
                f"heads: {n_heads}/{n_kv}, head_dim: {head_dim}"
            ),
        )
        m.add("Type", "NeuralNetwork")
        sections.append(m)

        # Input layer: shape is [channel:height:width] in NNTrainer; for token
        # IDs we use 1:1:seq_len which matches the existing C++ code path.
        inp = IniSection("input0")
        inp.add("Type", "input")
        inp.add("input_shape", f"1:1:{self.ctx.init_seq_len}")
        sections.append(inp)

        # Embedding (or tied with lm_head). The C++ ``tie_word_embeddings``
        # layer reuses one weight buffer for both embed and lm_head.
        emb_type = "tie_word_embeddings" if tie else "embedding_layer"
        emb = IniSection("embedding0")
        emb.add("Type", emb_type)
        emb.add("input_layers", "input0")
        emb.add("in_dim", vocab)
        emb.add("out_dim", hidden_size)
        sections.append(emb)

        prev = "embedding0"
        for i in range(num_layers):
            prev = self._emit_block(
                sections, i, prev,
                hidden_size=hidden_size,
                intermediate=intermediate,
                n_heads=n_heads,
                n_kv=n_kv,
                head_dim=head_dim,
                rope_theta=rope_theta,
                max_pos=max_pos,
                rms_eps=rms_eps,
            )

        # Final norm.
        out_norm = IniSection("output_norm")
        out_norm.add("Type", "rms_norm")
        out_norm.add("input_layers", prev)
        out_norm.add("epsilon", rms_eps)
        out_norm.add("packed", False)
        sections.append(out_norm)

        # LM head. Note: when using ``tie_word_embeddings`` the ``unit``
        # property is what switches the layer into "lm_head" mode (matrix
        # multiply against the shared embedding weight) rather than the
        # vocab-lookup mode used by the embedding instance.
        lm = IniSection("lm_head")
        if tie:
            lm.add("Type", "tie_word_embeddings")
            lm.add("input_layers", "output_norm")
            lm.add("unit", vocab)
            lm.add("disable_bias", True)
            # ``shared_from`` tells the runtime to point this layer's weight
            # at the embedding's weight instead of allocating fresh storage.
            lm.add("shared_from", "embedding0")
        else:
            lm.add("Type", "fully_connected")
            lm.add("input_layers", "output_norm")
            lm.add("unit", vocab)
            lm.add("disable_bias", True)
        sections.append(lm)

        return sections

    # ----- block helper ---------------------------------------------------
    def _emit_block(
        self,
        sections: list[IniSection],
        i: int,
        block_input: str,
        *,
        hidden_size: int,
        intermediate: int,
        n_heads: int,
        n_kv: int,
        head_dim: int,
        rope_theta: int,
        max_pos: int,
        rms_eps: float,
    ) -> str:
        """Emit one decoder block; return the name of its final tensor."""
        prefix = f"layer{i}"

        # Pre-attention RMSNorm.
        ans = IniSection(f"{prefix}_attention_norm")
        ans.add("Type", "rms_norm")
        ans.add("input_layers", block_input)
        ans.add("epsilon", rms_eps)
        ans.add("packed", False)
        sections.append(ans)

        # V then K then Q projections (matches C++ creation order so weight
        # buffers line up when falling back to sequential offset assignment).
        wv = IniSection(f"{prefix}_wv")
        wv.add("Type", "fully_connected")
        wv.add("input_layers", f"{prefix}_attention_norm")
        wv.add("unit", head_dim * n_kv)
        wv.add("disable_bias", True)
        sections.append(wv)

        wk = IniSection(f"{prefix}_wk")
        wk.add("Type", "fully_connected")
        wk.add("input_layers", f"{prefix}_attention_norm")
        wk.add("unit", head_dim * n_kv)
        wk.add("disable_bias", True)
        sections.append(wk)

        wq = IniSection(f"{prefix}_wq")
        wq.add("Type", "fully_connected")
        wq.add("input_layers", f"{prefix}_attention_norm")
        wq.add("unit", head_dim * n_heads)
        wq.add("disable_bias", True)
        sections.append(wq)

        # Q/K per-head reshaped RMSNorm (Qwen3 specific).
        kn = IniSection(f"{prefix}_k_norm")
        kn.add("Type", "reshaped_rms_norm")
        kn.add("input_layers", f"{prefix}_wk")
        kn.add("epsilon", rms_eps)
        kn.add("feature_size", head_dim)
        kn.add("packed", False)
        sections.append(kn)

        qn = IniSection(f"{prefix}_q_norm")
        qn.add("Type", "reshaped_rms_norm")
        qn.add("input_layers", f"{prefix}_wq")
        qn.add("epsilon", rms_eps)
        qn.add("feature_size", head_dim)
        qn.add("packed", False)
        sections.append(qn)

        # Attention core. mha_core takes (Q, K, V) as a multi-input layer.
        attn = IniSection(f"{prefix}_attention")
        attn.add("Type", "mha_core")
        # Order matches ``attn({q_normed, k_normed, v})`` in qwen3_causallm.cpp.
        attn.add("input_layers",
                 [f"{prefix}_q_norm", f"{prefix}_k_norm", f"{prefix}_wv"])
        attn.add("num_heads", n_heads)
        attn.add("num_heads_kv", n_kv)
        attn.add("max_timestep", self.ctx.max_seq_len)
        attn.add("rope_theta", rope_theta)
        attn.add("max_position_embeddings", max_pos)
        attn.add("max_new_tokens",
                 max(0, self.ctx.max_seq_len - self.ctx.init_seq_len))
        sections.append(attn)

        # O projection.
        wo = IniSection(f"{prefix}_attention_out")
        wo.add("Type", "fully_connected")
        wo.add("input_layers", f"{prefix}_attention")
        wo.add("unit", hidden_size)
        wo.add("disable_bias", True)
        sections.append(wo)

        # Residual: block_input + attention_out.
        rattn = IniSection(f"{prefix}_residual_attn")
        rattn.add("Type", "addition")
        rattn.add("input_layers", [block_input, f"{prefix}_attention_out"])
        sections.append(rattn)

        # FFN norm.
        fn = IniSection(f"{prefix}_ffn_norm")
        fn.add("Type", "rms_norm")
        fn.add("input_layers", f"{prefix}_residual_attn")
        fn.add("epsilon", rms_eps)
        fn.add("packed", False)
        sections.append(fn)

        # SwiGLU MLP: up + gate -> swiglu(up, gate) -> down.
        up = IniSection(f"{prefix}_ffn_up")
        up.add("Type", "fully_connected")
        up.add("input_layers", f"{prefix}_ffn_norm")
        up.add("unit", intermediate)
        up.add("disable_bias", True)
        sections.append(up)

        gate = IniSection(f"{prefix}_ffn_gate")
        gate.add("Type", "fully_connected")
        gate.add("input_layers", f"{prefix}_ffn_norm")
        gate.add("unit", intermediate)
        gate.add("disable_bias", True)
        sections.append(gate)

        sw = IniSection(f"{prefix}_ffn_swiglu")
        sw.add("Type", "swiglu")
        sw.add("input_layers", [f"{prefix}_ffn_up", f"{prefix}_ffn_gate"])
        sections.append(sw)

        down = IniSection(f"{prefix}_ffn_down")
        down.add("Type", "fully_connected")
        down.add("input_layers", f"{prefix}_ffn_swiglu")
        down.add("unit", hidden_size)
        down.add("disable_bias", True)
        sections.append(down)

        # Final residual: post-attn + ffn_down.
        rffn = IniSection(f"{prefix}_residual_ffn")
        rffn.add("Type", "addition")
        rffn.add("input_layers",
                 [f"{prefix}_residual_attn", f"{prefix}_ffn_down"])
        sections.append(rffn)

        return f"{prefix}_residual_ffn"

    # ----- weight bindings -------------------------------------------------
    def build_weight_bindings(self) -> list[WeightBinding]:
        cfg = self.cfg
        num_layers = int(self._require("num_hidden_layers"))
        tie = bool(cfg.get("tie_word_embeddings", False))

        # HF Qwen3 state_dict keys are prefixed with ``model.``; the LM head is
        # ``lm_head.weight`` at the top level (only when not tied).
        b: list[WeightBinding] = []
        # Embedding: HF stores [vocab, hidden]; nntrainer's embedding_layer
        # consumes the same shape — no transpose needed.
        b.append(WeightBinding(
            hf_key="model.embed_tokens.weight",
            nntr_key="embedding0:Embedding",
            transpose=False,
        ))

        for i in range(num_layers):
            p = f"layer{i}"
            hp = f"model.layers.{i}"
            # Norms (single gamma vector each; no transpose).
            b.append(WeightBinding(
                f"{hp}.input_layernorm.weight", f"{p}_attention_norm:gamma"))
            b.append(WeightBinding(
                f"{hp}.post_attention_layernorm.weight", f"{p}_ffn_norm:gamma"))
            # Q/K/V/O projections: HF stores [out, in]; FC layer expects
            # [in, out] -> transpose.
            b.append(WeightBinding(
                f"{hp}.self_attn.q_proj.weight", f"{p}_wq:weight",
                transpose=True))
            b.append(WeightBinding(
                f"{hp}.self_attn.k_proj.weight", f"{p}_wk:weight",
                transpose=True))
            b.append(WeightBinding(
                f"{hp}.self_attn.v_proj.weight", f"{p}_wv:weight",
                transpose=True))
            b.append(WeightBinding(
                f"{hp}.self_attn.o_proj.weight",
                f"{p}_attention_out:weight",
                transpose=True))
            # Q/K per-head norms.
            b.append(WeightBinding(
                f"{hp}.self_attn.q_norm.weight", f"{p}_q_norm:gamma"))
            b.append(WeightBinding(
                f"{hp}.self_attn.k_norm.weight", f"{p}_k_norm:gamma"))
            # MLP.
            b.append(WeightBinding(
                f"{hp}.mlp.up_proj.weight", f"{p}_ffn_up:weight",
                transpose=True))
            b.append(WeightBinding(
                f"{hp}.mlp.gate_proj.weight", f"{p}_ffn_gate:weight",
                transpose=True))
            b.append(WeightBinding(
                f"{hp}.mlp.down_proj.weight", f"{p}_ffn_down:weight",
                transpose=True))

        # Output norm.
        b.append(WeightBinding("model.norm.weight", "output_norm:gamma"))
        # LM head: when tied, the embedding weight is reused — nntrainer's
        # tie_word_embeddings layer resolves ``shared_from`` so we omit a
        # binding here. When untied, transpose from [vocab, hidden].
        if not tie:
            b.append(WeightBinding(
                "lm_head.weight", "lm_head:weight", transpose=True))
        return b


register("qwen3", Qwen3Builder)
