#!/usr/bin/env python3
"""
NNTrainer model importer for TorchFXConverter output.

Provides a high-level Python interface that converts a HuggingFace model
to NNTrainer format and validates it using the standalone ``nntr_runner``
executable. No per-model C++ compilation is required.

Typical workflow
----------------
1. ``converter.py`` converts a HuggingFace model to INI + optional weights.
2. ``nntr_runner`` loads the INI (and optionally the weight binary) to verify
   that NNTrainer can compile and initialize the model graph.

This module exposes two main entry points:

* :func:`import_model`   — one-shot: convert + run with nntr_runner.
* :class:`NNTrainerImporter` — stateful class for fine-grained control.

Usage (CLI)
-----------
::

    # Convert and verify with nntr_runner (INI only):
    python importer.py --model Qwen/Qwen3-0.6B --output ./out/

    # Convert, export weights, and verify:
    python importer.py --model Qwen/Qwen3-0.6B --output ./out/ --weights

    # Verify a previously converted INI without reconverting:
    python importer.py --ini ./out/qwen3.ini

Usage (Python API)
------------------
::

    from importer import NNTrainerImporter

    imp = NNTrainerImporter(build_dir="./builddir")
    result = imp.convert_and_run("Qwen/Qwen3-0.6B", output_dir="./out/")
    print(result.summary)   # NNTrainer model summary
    assert result.success
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from dataclasses import dataclass, field
from typing import List, Optional

# Ensure sibling modules are importable when run from any working directory.
_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

# Default locations (relative to the nntrainer repo root)
_NNTRAINER_ROOT = os.path.abspath(os.path.join(_HERE, "..", ".."))
_DEFAULT_BUILD_DIR = os.path.join(_NNTRAINER_ROOT, "builddir")
_NNTR_RUNNER_REL = os.path.join(
    "Applications", "TorchFXConverter", "jni", "nntr_runner"
)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class ImportResult:
    """Result of a convert-and-run operation."""

    success: bool
    """True if nntr_runner exited with code 0."""

    ini_path: str = ""
    """Path to the generated INI file."""

    bin_path: str = ""
    """Path to the generated weight binary (empty if not exported)."""

    summary: str = ""
    """stdout from nntr_runner (includes NNTrainer model summary)."""

    error: str = ""
    """stderr from nntr_runner on failure."""

    converted_files: List[str] = field(default_factory=list)
    """All files generated by the converter."""


# ---------------------------------------------------------------------------
# Core importer class
# ---------------------------------------------------------------------------

class NNTrainerImporter:
    """High-level importer: convert HuggingFace model → run with nntr_runner.

    Parameters
    ----------
    build_dir:
        Path to the NNTrainer meson build directory (contains ``nntr_runner``).
    seq_len:
        Sequence length used when tracing the model.
    batch_size:
        Batch size written into the INI ``[Model]`` section.
    dtype:
        Weight dtype for conversion (``"float32"`` or ``"float16"``).
    """

    def __init__(
        self,
        build_dir: str = _DEFAULT_BUILD_DIR,
        seq_len: int = 8,
        batch_size: int = 1,
        dtype: str = "float32",
    ) -> None:
        self.build_dir = build_dir
        self.seq_len = seq_len
        self.batch_size = batch_size
        self.dtype = dtype

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def convert_and_run(
        self,
        model_name_or_path: str,
        output_dir: str,
        export_weights: bool = False,
        model_name: Optional[str] = None,
        verbose: bool = True,
    ) -> ImportResult:
        """Convert a HuggingFace model and verify it with nntr_runner.

        Steps
        -----
        1. Run ``converter.py --format all`` to produce INI + JSON + C++
           header/source in *output_dir*, plus optionally a weight binary.
        2. Pass *output_dir* directly to ``nntr_runner`` which auto-discovers
           the files and runs a full inference pass — just like
           ``nntr_causallm <model_dir/>``.

        Parameters
        ----------
        model_name_or_path:
            HuggingFace model ID (e.g. ``"Qwen/Qwen3-0.5B"``) or a local
            directory containing ``config.json``.
        output_dir:
            Directory where converted files are written.
        export_weights:
            If True, also convert and save model weights to a ``.bin`` file.
        model_name:
            Override the output file basename (default: derived from the model
            path).
        verbose:
            Print progress to stdout.

        Returns
        -------
        ImportResult
            Populated with success flag, file paths, and nntr_runner output.
        """
        os.makedirs(output_dir, exist_ok=True)

        # Step 1: convert (all formats so nntr_runner gets INI + JSON + header)
        if verbose:
            print(f"[importer] Converting: {model_name_or_path}")
        ok, converted_files, err = self._run_converter(
            model_name_or_path, output_dir,
            export_weights=export_weights,
            model_name=model_name,
            verbose=verbose,
        )
        if not ok:
            return ImportResult(
                success=False,
                error=f"Converter failed:\n{err}",
                converted_files=converted_files,
            )

        if not any(f.endswith(".ini") for f in converted_files):
            return ImportResult(
                success=False,
                error="Converter did not produce an INI file.",
                converted_files=converted_files,
            )

        if verbose:
            print(f"[importer] Running nntr_runner on: {output_dir}")

        # Step 2: pass the output directory directly to nntr_runner
        result = self._run_nntr_runner_dir(output_dir, verbose=verbose)
        result.converted_files = converted_files
        result.ini_path = self._find_file(converted_files, ".ini")
        result.bin_path = self._find_file(converted_files, ".bin")
        return result

    def run_dir(
        self,
        output_dir: str,
        verbose: bool = True,
    ) -> ImportResult:
        """Run nntr_runner on a directory of converter output files.

        Pass the directory produced by ``converter.py --format all``
        directly — nntr_runner auto-discovers the INI, JSON, header,
        and weight binary inside.

        Parameters
        ----------
        output_dir:
            Directory containing converter output (*.ini, *.json, *.h, *.bin).
        verbose:
            Print progress to stdout.

        Returns
        -------
        ImportResult
        """
        if verbose:
            print(f"[importer] Running nntr_runner on: {output_dir}")
        return self._run_nntr_runner_dir(output_dir, verbose=verbose)

    def run_ini(
        self,
        ini_path: str,
        bin_path: str = "",
        verbose: bool = True,
    ) -> ImportResult:
        """Run an already-converted INI file with nntr_runner.

        Parameters
        ----------
        ini_path:
            Path to a NNTrainer INI configuration file.
        bin_path:
            Path to a weight binary file (empty = no weights loaded).
        verbose:
            Print progress to stdout.

        Returns
        -------
        ImportResult
        """
        if verbose:
            print(f"[importer] Running nntr_runner: {ini_path}")
        cmd = [ini_path]
        if bin_path:
            cmd.append(bin_path)
        return self._run_nntr_runner(cmd, ini_path=ini_path,
                                     bin_path=bin_path, verbose=verbose)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _nntr_runner_path(self) -> str:
        """Return the absolute path to the nntr_runner executable."""
        return os.path.join(self.build_dir, _NNTR_RUNNER_REL)

    def _run_converter(
        self,
        model_name_or_path: str,
        output_dir: str,
        export_weights: bool,
        model_name: Optional[str],
        verbose: bool,
    ):
        """Invoke converter.py and return (ok, files, stderr).

        Uses ``--format all`` so nntr_runner gets the full set of files
        (INI, JSON, C++ header+source) in one shot.
        """
        converter_script = os.path.join(_HERE, "converter.py")
        cmd = [
            sys.executable, converter_script,
            "--model", model_name_or_path,
            "--output", output_dir,
            "--format", "all",
            "--seq-len", str(self.seq_len),
            "--batch-size", str(self.batch_size),
        ]
        if export_weights:
            cmd += ["--weights", "--dtype", self.dtype]
        if model_name:
            cmd += ["--model-name", model_name]
        if not verbose:
            cmd.append("--quiet")

        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=300
        )
        if verbose and result.stdout:
            print(result.stdout, end="")

        files = []
        if os.path.isdir(output_dir):
            files = [
                os.path.join(output_dir, f)
                for f in os.listdir(output_dir)
            ]

        return result.returncode == 0, files, result.stderr

    def _make_env(self) -> dict:
        """Build LD_LIBRARY_PATH environment for running nntr_runner."""
        env = os.environ.copy()
        lib_paths = [
            os.path.join(self.build_dir, "nntrainer"),
            os.path.join(self.build_dir, "Applications", "CausalLM", "layers"),
        ]
        env["LD_LIBRARY_PATH"] = ":".join(
            [p for p in lib_paths if os.path.isdir(p)]
            + [env.get("LD_LIBRARY_PATH", "")]
        ).rstrip(":")
        return env

    def _check_runner(self) -> Optional[str]:
        """Return error string if nntr_runner is missing, else None."""
        runner = self._nntr_runner_path()
        if not os.path.isfile(runner):
            return (
                f"nntr_runner not found: {runner}\n"
                "Build NNTrainer first:\n"
                "  meson setup builddir\n"
                "  ninja -C builddir "
                "Applications/TorchFXConverter/jni/nntr_runner"
            )
        return None

    def _run_nntr_runner_dir(
        self,
        output_dir: str,
        verbose: bool,
    ) -> ImportResult:
        """Run nntr_runner with a directory argument (primary usage).

        nntr_runner auto-discovers *.ini, *.json, *.h, *.bin inside the
        directory — mirrors how ``nntr_causallm <model_dir/>`` is used.
        """
        err = self._check_runner()
        if err:
            return ImportResult(success=False, error=err)

        runner = self._nntr_runner_path()
        result = subprocess.run(
            [runner, output_dir],
            capture_output=True, text=True,
            timeout=120, env=self._make_env(),
        )

        if verbose:
            if result.stdout:
                print(result.stdout, end="")
            if result.returncode != 0 and result.stderr:
                print(result.stderr, end="", file=sys.stderr)

        return ImportResult(
            success=result.returncode == 0,
            summary=result.stdout,
            error=result.stderr if result.returncode != 0 else "",
        )

    def _run_nntr_runner(
        self,
        extra_args: List[str],
        ini_path: str = "",
        bin_path: str = "",
        verbose: bool = True,
    ) -> ImportResult:
        """Run nntr_runner with explicit file arguments."""
        err = self._check_runner()
        if err:
            return ImportResult(success=False, ini_path=ini_path,
                                bin_path=bin_path, error=err)

        runner = self._nntr_runner_path()
        result = subprocess.run(
            [runner] + extra_args,
            capture_output=True, text=True,
            timeout=120, env=self._make_env(),
        )

        if verbose:
            if result.stdout:
                print(result.stdout, end="")
            if result.returncode != 0 and result.stderr:
                print(result.stderr, end="", file=sys.stderr)

        return ImportResult(
            success=result.returncode == 0,
            ini_path=ini_path,
            bin_path=bin_path,
            summary=result.stdout,
            error=result.stderr if result.returncode != 0 else "",
        )

    @staticmethod
    def _find_file(paths: List[str], ext: str) -> str:
        """Return the first path in *paths* that ends with *ext*."""
        for p in paths:
            if p.endswith(ext):
                return p
        return ""


# ---------------------------------------------------------------------------
# Convenience function
# ---------------------------------------------------------------------------

def import_model(
    model_name_or_path: str,
    output_dir: str,
    build_dir: str = _DEFAULT_BUILD_DIR,
    export_weights: bool = False,
    seq_len: int = 8,
    dtype: str = "float32",
    verbose: bool = True,
) -> ImportResult:
    """Convert a HuggingFace model and verify it with nntr_runner.

    Convenience wrapper around :class:`NNTrainerImporter`.

    Parameters
    ----------
    model_name_or_path:
        HuggingFace model ID or local directory.
    output_dir:
        Directory for converted files.
    build_dir:
        NNTrainer build directory (must contain ``nntr_runner``).
    export_weights:
        Also convert and save model weights.
    seq_len:
        Sequence length for tracing.
    dtype:
        Weight dtype (``"float32"`` or ``"float16"``).
    verbose:
        Print progress.

    Returns
    -------
    ImportResult
    """
    importer = NNTrainerImporter(
        build_dir=build_dir, seq_len=seq_len, dtype=dtype
    )
    return importer.convert_and_run(
        model_name_or_path,
        output_dir=output_dir,
        export_weights=export_weights,
        verbose=verbose,
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a HuggingFace model and verify with nntr_runner.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--model",
        metavar="MODEL",
        help="HuggingFace model ID or local path to convert.",
    )
    group.add_argument(
        "--dir",
        metavar="DIR",
        help="Run nntr_runner on an existing converter output directory "
             "(skips conversion).",
    )
    group.add_argument(
        "--ini",
        metavar="INI",
        help="Path to an existing NNTrainer INI file (skip conversion).",
    )
    parser.add_argument(
        "--output",
        metavar="DIR",
        default="./nntr_output",
        help="Output directory for converted files (used with --model).",
    )
    parser.add_argument(
        "--build-dir",
        metavar="DIR",
        default=_DEFAULT_BUILD_DIR,
        help="NNTrainer build directory containing nntr_runner.",
    )
    parser.add_argument(
        "--weights",
        action="store_true",
        help="Also convert and save model weights (.bin).",
    )
    parser.add_argument(
        "--bin",
        metavar="BIN",
        default="",
        help="Path to weight binary (used with --ini).",
    )
    parser.add_argument(
        "--seq-len",
        type=int,
        default=8,
        metavar="N",
        help="Sequence length for model tracing.",
    )
    parser.add_argument(
        "--dtype",
        choices=["float32", "float16"],
        default="float32",
        help="Weight dtype.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress progress output.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    verbose = not args.quiet
    importer = NNTrainerImporter(
        build_dir=args.build_dir,
        seq_len=args.seq_len,
        dtype=args.dtype,
    )

    if args.dir:
        result = importer.run_dir(args.dir, verbose=verbose)
    elif args.ini:
        result = importer.run_ini(args.ini, bin_path=args.bin, verbose=verbose)
    else:
        result = importer.convert_and_run(
            args.model,
            output_dir=args.output,
            export_weights=args.weights,
            verbose=verbose,
        )

    if not result.success:
        print(f"\n[importer] FAILED:\n{result.error}", file=sys.stderr)
        return 1

    print(f"\n[importer] SUCCESS — model initialized and inference passed.")
    if result.ini_path:
        print(f"  INI    : {result.ini_path}")
    if result.bin_path:
        print(f"  Weights: {result.bin_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
