// Auto-generated by TorchFX-to-NNTrainer converter
// Model: bert (encoder_only)
// Inherits from causallm::Transformer

#ifndef __MULTILINGUAL_TINYBERT_16MB_H__
#define __MULTILINGUAL_TINYBERT_16MB_H__

#include "transformer.h"

namespace causallm {

/**
 * @brief BertModel Class
 * @note Auto-generated from HuggingFace bert model
 */
class BertModel : public Transformer {

public:
  BertModel(json &cfg, json &generation_cfg, json &nntr_cfg)
    : Transformer(cfg, generation_cfg, nntr_cfg, ModelType::EMBEDDING),
      saved_cfg(cfg), saved_gen_cfg(generation_cfg), saved_nntr_cfg(nntr_cfg) {}

  void initialize() override;
  void setupParameters(json &cfg, json &generation_cfg,
                       json &nntr_cfg) override;
  void constructModel() override;
  Tensor createTransformerDecoderBlock(const int layer_id,
                                      Tensor input) override;
  Tensor createAttention(const int layer_id, int seq_len,
                         int n_heads, int head_dim,
                         Tensor query, Tensor key,
                         Tensor value) override;
  Tensor createMlp(const int layer_id, int dim,
                   int hidden_dim, Tensor input) override;
  void registerCustomLayers() override;

  /**
   * @brief Test constructor with minimal config
   * @note Creates model with small dimensions for testing
   */
  static BertModel createTestModel();

  ModelHandle &getModel() { return model; }

private:
  json saved_cfg;
  json saved_gen_cfg;
  json saved_nntr_cfg;
};

} // namespace causallm

#endif // __MULTILINGUAL_TINYBERT_16MB_H__
