// Auto-generated by TorchFX-to-NNTrainer converter
// Model: bert (encoder_only)
// Inherits from causallm::Transformer

#include "multilingual_tinybert_16mb.h"
#include <model.h>
#include <tensor_api.h>
#include <app_context.h>
#include <engine.h>

#include <embedding_layer.h>
#include <mha_core.h>
#include <tie_word_embedding.h>

#include <sstream>
#include <codecvt>
#include <locale>

#include <iomanip>
#include <sstream>

static std::string toStringPrecise(float v) {
  std::ostringstream oss;
  oss << std::setprecision(20) << v;
  return oss.str();
}

using ml::train::createLayer;
using ml::train::Tensor;
using LayerHandle = ml::train::LayerHandle;

template <typename T>
static std::string withKey(const std::string &key, T val) {
  return key + "=" + std::to_string(val);
}

template <>
std::string withKey(const std::string &key, std::string val) {
  return key + "=" + val;
}

template <>
std::string withKey(const std::string &key, const char *val) {
  return key + "=" + std::string(val);
}

namespace causallm {

std::vector<float *>
BertModel::encode(const WSTR prompt,
                  const WSTR system_prompt,
                  const WSTR tail_prompt) {
  if (!is_initialized) {
    throw std::runtime_error(
      "BertModel is not initialized. Please call initialize() before run().");
  }

  #if defined(_WIN32)
    std::wstring prompt_ = system_prompt + prompt + tail_prompt;
    std::wstring_convert<std::codecvt_utf8<wchar_t>> converter;
    auto tokenized = tokenizer->Encode(converter.to_bytes(prompt_), true);
#else
    std::string prompt_ = system_prompt + prompt + tail_prompt;
    auto tokenized = tokenizer->Encode(prompt_, true);
#endif

  std::vector<unsigned int> input_ids;
  unsigned int input_len =
    std::min(static_cast<unsigned int>(tokenized.size()), INIT_SEQ_LEN);

  for (unsigned int i = 0; i < input_len; ++i) {
    input_ids.push_back(static_cast<unsigned int>(tokenized[i]));
  }

  float *input_sample =
    (float *)malloc(sizeof(float) * BATCH_SIZE * INIT_SEQ_LEN);
  float *position_ids =
    (float *)malloc(sizeof(float) * BATCH_SIZE * INIT_SEQ_LEN);
  float *token_type_ids =
    (float *)malloc(sizeof(float) * BATCH_SIZE * INIT_SEQ_LEN);

  if (!input_sample || !position_ids || !token_type_ids) {
    free(input_sample);
    free(position_ids);
    free(token_type_ids);
    throw std::runtime_error("Failed to allocate input buffers");
  }

  std::fill(input_sample, input_sample + BATCH_SIZE * INIT_SEQ_LEN, 0.0f);
  std::fill(position_ids, position_ids + BATCH_SIZE * INIT_SEQ_LEN, 0.0f);
  std::fill(token_type_ids, token_type_ids + BATCH_SIZE * INIT_SEQ_LEN, 0.0f);

  for (unsigned int b = 0; b < BATCH_SIZE; ++b) {
    for (unsigned int i = 0; i < input_len; ++i) {
      input_sample[static_cast<size_t>(b) * INIT_SEQ_LEN + i] =
        static_cast<float>(input_ids[i]);
      position_ids[static_cast<size_t>(b) * INIT_SEQ_LEN + i] =
        static_cast<float>(i);
      token_type_ids[static_cast<size_t>(b) * INIT_SEQ_LEN + i] = 0.0f;
    }
  }

  std::vector<float *> input = {input_sample, position_ids, token_type_ids};
  std::vector<float *> label;
  unsigned int init_len = input.size();
  auto output = model->incremental_inference(BATCH_SIZE, input, label, init_len,
                                        SYS_PROMP_LEN,
                                        SYS_PROMP_LEN + input_len, false);

  free(input_sample);
  free(position_ids);
  free(token_type_ids);

  return output;
}

BertModel::BertModel(json &cfg, json &generation_cfg,
                                         json &nntr_cfg) :
  Transformer(cfg, generation_cfg, nntr_cfg, ModelType::EMBEDDING) {
  setupParameters(cfg, generation_cfg, nntr_cfg);
}

void BertModel::setupParameters(json &cfg, json &generation_cfg,
                              json &nntr_cfg) {
  Transformer::setupParameters(cfg, generation_cfg, nntr_cfg);

  IS_CAUSAL = false;
  NORM_EPS = cfg.value("layer_norm_eps", 1e-12f);
  ROPE_THETA = 0;  // No RoPE for this model
}

void BertModel::constructModel() {

  using ml::train::createLayer;

  // Input layer
  LayerHandle input_layer(createLayer("input", {
    withKey("name", "input0"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  }));
  Tensor input = input_layer(Tensor());
  std::vector<Tensor> all_inputs = {input};

  // Position IDs input
  LayerHandle pos_input(createLayer("input", {
    withKey("name", "position_ids"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  }));
  Tensor pos_ids = pos_input(Tensor());
  all_inputs.push_back(pos_ids);

  // Token type IDs input
  LayerHandle tt_input(createLayer("input", {
    withKey("name", "token_type_ids"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  }));
  Tensor tt_ids = tt_input(Tensor());
  all_inputs.push_back(tt_ids);

  // Token embedding
  const std::string embedding_type = TIE_WORD_EMBEDDINGS ? "tie_word_embeddings" : "embedding_layer";
  LayerHandle word_emb(createLayer(embedding_type, {
    withKey("name", "embedding0"),
    withKey("in_dim", NUM_VOCAB),
    withKey("out_dim", DIM)
  }));
  Tensor x = word_emb(input);

  // Position embedding
  LayerHandle pos_emb(createLayer("embedding_layer", {
    withKey("name", "position_embedding"),
    withKey("in_dim", MAX_POSITION_EMBEDDINGS),
    withKey("out_dim", DIM)
  }));
  Tensor pos_out = pos_emb(pos_ids);
  x = x.add(pos_out);

  // Token type embedding
  LayerHandle tt_emb(createLayer("embedding_layer", {
    withKey("name", "token_type_embedding"),
    withKey("in_dim", 2),
    withKey("out_dim", DIM)
  }));
  Tensor tt_out = tt_emb(tt_ids);
  x = x.add(tt_out);

  // Post-embedding normalization
  LayerHandle emb_norm(createLayer("layer_normalization", {
    withKey("name", "embedding_norm"),
    withKey("epsilon", toStringPrecise(NORM_EPS)),
    withKey("axis", 3)
  }));
  x = emb_norm(x);

  // Transformer encoder blocks
  for (int i = 0; i < NUM_LAYERS; ++i) {
    x = createTransformerDecoderBlock(i, x);
  }

  // Compile model from symbolic tensor graph
  std::vector<Tensor> outputs = {x};
  model->compile(all_inputs, outputs, ml::train::ExecutionMode::INFERENCE);
}

Tensor
BertModel::createTransformerDecoderBlock(const int layer_id,
                                      Tensor input) {

  using ml::train::createLayer;

  // Self attention
  Tensor att_out =
    createAttention(layer_id, INIT_SEQ_LEN, NUM_HEADS, HEAD_DIM,
                    input, input, input);

  // Attention residual + post-norm
  Tensor residual = input.add(att_out);
  LayerHandle att_norm(createLayer("layer_normalization", {
    withKey("name", "layer" + std::to_string(layer_id) + "_attention_norm"),
    withKey("epsilon", toStringPrecise(NORM_EPS)),
    withKey("axis", 3)
  }));
  Tensor normed = att_norm(residual);

  // Feed forward
  Tensor ffn_out = createMlp(layer_id, DIM, INTERMEDIATE_SIZE, normed);

  // FFN residual + post-norm
  Tensor ffn_residual = normed.add(ffn_out);
  LayerHandle ffn_norm(createLayer("layer_normalization", {
    withKey("name", "layer" + std::to_string(layer_id) + "_ffn_norm"),
    withKey("epsilon", toStringPrecise(NORM_EPS)),
    withKey("axis", 3)
  }));
  Tensor block_out = ffn_norm(ffn_residual);

  return block_out;
}

Tensor
BertModel::createAttention(const int layer_id, int seq_len,
                         int n_heads, int head_dim,
                         Tensor query, Tensor key,
                         Tensor value) {

  using ml::train::createLayer;

  auto V_name = "layer" + std::to_string(layer_id) + "_wv";
  auto K_name = "layer" + std::to_string(layer_id) + "_wk";
  auto Q_name = "layer" + std::to_string(layer_id) + "_wq";
  auto A_name = "layer" + std::to_string(layer_id) + "_attention";
  auto O_name = "layer" + std::to_string(layer_id) + "_attention_out";

  // V projection
  LayerHandle v_proj(createLayer("fully_connected", {
    withKey("name", V_name),
    withKey("unit", head_dim * n_heads / GQA_SIZE),
    withKey("disable_bias", "false")
  }));
  Tensor v = v_proj(value);

  // K projection
  LayerHandle k_proj(createLayer("fully_connected", {
    withKey("name", K_name),
    withKey("unit", head_dim * n_heads / GQA_SIZE),
    withKey("disable_bias", "false")
  }));
  Tensor k = k_proj(key);

  // Q projection
  LayerHandle q_proj(createLayer("fully_connected", {
    withKey("name", Q_name),
    withKey("unit", head_dim * n_heads),
    withKey("disable_bias", "false")
  }));
  Tensor q = q_proj(query);

  // Attention core layer
  std::vector<std::string> attn_props = {
    withKey("name", A_name),
    withKey("num_heads", n_heads),
    withKey("num_heads_kv", n_heads / GQA_SIZE),
    withKey("max_timestep", std::to_string(INIT_SEQ_LEN)),
    withKey("is_causal", IS_CAUSAL ? "true" : "false"),
    withKey("rope_theta", ROPE_THETA),
  };
  LayerHandle attn(createLayer("mha_core", attn_props));
  Tensor a = attn({q, k, v});

  // O projection
  LayerHandle o_proj(createLayer("fully_connected", {
    withKey("name", O_name),
    withKey("unit", DIM),
    withKey("disable_bias", "false")
  }));
  Tensor o = o_proj(a);

  return o;
}

void BertModel::registerCustomLayers() {
  Transformer::registerCustomLayers();
}

Tensor BertModel::createMlp(
  const int layer_id, int dim, int hidden_dim,
  Tensor input) {

  using ml::train::createLayer;

  LayerHandle ffn_fc1(createLayer("fully_connected", {withKey("name", "layer" + std::to_string(layer_id) + "_ffn_fc1"), withKey("unit", hidden_dim)}));
  Tensor ffn_fc1_out = ffn_fc1(input);

  LayerHandle ffn_act(createLayer("activation", {withKey("name", "layer" + std::to_string(layer_id) + "_ffn_act"), withKey("activation", "gelu")}));
  Tensor ffn_act_out = ffn_act(ffn_fc1_out);

  LayerHandle ffn_down(createLayer("fully_connected", {withKey("name", "layer" + std::to_string(layer_id) + "_ffn_down"), withKey("unit", dim)}));
  Tensor ffn_down_out = ffn_down(ffn_act_out);

  return ffn_down_out;
}

BertModel BertModel::createTestModel() {
  // Minimal JSON config for testing
  json cfg;
  cfg["vocab_size"] = 119547;
  cfg["hidden_size"] = 32;
  cfg["num_hidden_layers"] = 2;
  cfg["num_attention_heads"] = 4;
  cfg["num_key_value_heads"] = 4;
  cfg["head_dim"] = 8;
  cfg["intermediate_size"] = 128;
  cfg["layer_norm_eps"] = 1e-12;
  cfg["tie_word_embeddings"] = true;
  cfg["max_position_embeddings"] = 512;
  cfg["is_causal"] = false;

  json gen_cfg;
  gen_cfg["max_new_tokens"] = 0;

  json nntr_cfg;
  nntr_cfg["init_seq_len"] = 8;
  nntr_cfg["batch_size"] = 1;
  nntr_cfg["model_tensor_type"] = "FP32-FP32";
  nntr_cfg["memory_swap"] = false;
  nntr_cfg["tokenizer_file"] = "";

  return BertModel(cfg, gen_cfg, nntr_cfg);
}

void BertModel::run(const WSTR prompt, bool do_sample,
                    const WSTR system_prompt, const WSTR tail_prompt,
                    bool log_output) {
  (void)do_sample;

  try {
    std::vector<float *> results = encode(prompt, system_prompt, tail_prompt);

    if (log_output) {

      std::cout << "Embedding Result (" << BATCH_SIZE
                << " batch(es)):" << std::endl;
      for (unsigned int b = 0; b < BATCH_SIZE; ++b) {
        std::cout << "Batch " << b << ": [";
        // Print first few elements as sample
        int print_dim = (DIM > 10) ? 10 : DIM;
        for (int i = 0; i < print_dim; ++i) {
          std::cout << results[0][b * DIM + i]
                    << (i == print_dim - 1 ? "" : ", ");
        }
        if (DIM > 10)
          std::cout << ", ...";
        std::cout << "] (Total DIM: " << DIM << ")" << std::endl;
      }
    }

    // output should be deallocated after use.
    for (auto out : results) {
      delete[] out;
    }
  } catch (const std::exception &e) {
    std::cerr << "Error during BertModel run: " << e.what() << std::endl;
  }
}

} // namespace causallm
