// Auto-generated by TorchFX-to-NNTrainer converter
// Model: bert (encoder_only)
// Inherits from causallm::Transformer

#include "multilingual_tinybert_16mb.h"
#include <model.h>
#include <tensor_api.h>
#include <app_context.h>
#include <engine.h>
#include <iomanip>
#include <sstream>

#include <embedding_layer.h>
#include <mha_core.h>
#include <tie_word_embedding.h>

using ml::train::createLayer;
using ml::train::Tensor;
using LayerHandle = ml::train::LayerHandle;

template <typename T>
static std::string withKey(const std::string &key, T val) {
  return key + "=" + std::to_string(val);
}

// Float specialization: use scientific notation to avoid precision loss
// (e.g. std::to_string(1e-12f) gives "0.000000" which fails epsilon > 0 check)
template <>
std::string withKey(const std::string &key, float val) {
  std::ostringstream oss;
  oss << key << "=" << std::scientific << std::setprecision(10) << val;
  return oss.str();
}

template <>
std::string withKey(const std::string &key, std::string val) {
  return key + "=" + val;
}

template <>
std::string withKey(const std::string &key, const char *val) {
  return key + "=" + std::string(val);
}

namespace causallm {

void BertModel::initialize() {
  // Re-apply BERT-specific parameters. The Transformer base constructor calls
  // Transformer::setupParameters() (not BertModel::setupParameters()) due to
  // C++ constructor vtable rules, so BERT-specific settings are applied here.
  BertModel::setupParameters(saved_cfg, saved_gen_cfg, saved_nntr_cfg);

  // Register custom layers
  registerCustomLayers();

  // Create model and set properties
  model = ml::train::createModel(ml::train::ModelType::NEURAL_NET);
  std::vector<std::string> model_props = {
    withKey("batch_size", BATCH_SIZE), withKey("epochs", "1"),
    withKey("model_tensor_type", MODEL_TENSOR_TYPE)};
  model->setProperty(model_props);

  // constructModel() uses the symbolic tensor API which calls
  // compile() + initialize() + allocate() internally in one shot.
  // So we must NOT call model->initialize() again after constructModel().
  try {
    constructModel();
  } catch (const std::exception &e) {
    throw std::invalid_argument(
      std::string("BertModel construction failed: ") + e.what());
  }

  is_initialized = true;
}

void BertModel::setupParameters(json &cfg, json &generation_cfg,
                              json &nntr_cfg) {

  // nntrainer parameters
  BATCH_SIZE = nntr_cfg["batch_size"].get<unsigned int>();
  MODEL_TENSOR_TYPE = nntr_cfg["model_tensor_type"].get<std::string>();
  INIT_SEQ_LEN = nntr_cfg["init_seq_len"];
  MAX_SEQ_LEN = nntr_cfg.value("max_seq_len", INIT_SEQ_LEN);
  NUM_TO_GENERATE = nntr_cfg.value("num_to_generate", 0);
  MEMORY_SWAP = nntr_cfg.value("fsu", false);
  FSU_LOOKAHEAD = nntr_cfg.value("fsu_lookahead", 1u);
  EMBEDDING_DTYPE = nntr_cfg.value("embedding_dtype", MODEL_TENSOR_TYPE);
  FC_LAYER_DTYPE = nntr_cfg.value("fc_layer_dtype", MODEL_TENSOR_TYPE);

  // Encoder-only model: bidirectional attention
  IS_CAUSAL = false;

  // Model architecture parameters
  NUM_VOCAB = cfg["vocab_size"];
  DIM = cfg["hidden_size"];
  INTERMEDIATE_SIZE = cfg["intermediate_size"];
  NUM_LAYERS = cfg["num_hidden_layers"];
  NUM_HEADS = cfg["num_attention_heads"];
  HEAD_DIM = cfg.value("head_dim", DIM / NUM_HEADS);
  NUM_KEY_VALUE_HEADS = cfg.value("num_key_value_heads", NUM_HEADS);
  MAX_POSITION_EMBEDDINGS = cfg.value("max_position_embeddings", 512u);
  TIE_WORD_EMBEDDINGS = cfg.value("tie_word_embeddings", false);
  NORM_EPS = cfg.value("layer_norm_eps", 1e-12f);
  ROPE_THETA = 0;  // No RoPE for this model
  GQA_SIZE = NUM_HEADS / NUM_KEY_VALUE_HEADS;
  SLIDING_WINDOW = cfg.value("sliding_window", UINT_MAX);
}

void BertModel::constructModel() {

  using ml::train::createLayer;

  // Input layer
  LayerHandle input_layer(createLayer("input", {
    withKey("name", "input0"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  }));
  Tensor input = input_layer(Tensor());
  std::vector<Tensor> all_inputs = {input};

  // Position IDs input
  LayerHandle pos_input(createLayer("input", {
    withKey("name", "position_ids"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  }));
  Tensor pos_ids = pos_input(Tensor());
  all_inputs.push_back(pos_ids);

  // Token type IDs input
  LayerHandle tt_input(createLayer("input", {
    withKey("name", "token_type_ids"),
    withKey("input_shape", "1:1:" + std::to_string(INIT_SEQ_LEN))
  }));
  Tensor tt_ids = tt_input(Tensor());
  all_inputs.push_back(tt_ids);

  // Token embedding
  const std::string embedding_type = TIE_WORD_EMBEDDINGS ? "tie_word_embeddings" : "embedding_layer";
  LayerHandle word_emb(createLayer(embedding_type, {
    withKey("name", "embedding0"),
    withKey("in_dim", NUM_VOCAB),
    withKey("out_dim", DIM)
  }));
  Tensor x = word_emb(input);

  // Position embedding
  LayerHandle pos_emb(createLayer("embedding_layer", {
    withKey("name", "position_embedding"),
    withKey("in_dim", MAX_POSITION_EMBEDDINGS),
    withKey("out_dim", DIM)
  }));
  Tensor pos_out = pos_emb(pos_ids);
  x = x.add(pos_out);

  // Token type embedding
  LayerHandle tt_emb(createLayer("embedding_layer", {
    withKey("name", "token_type_embedding"),
    withKey("in_dim", 2),
    withKey("out_dim", DIM)
  }));
  Tensor tt_out = tt_emb(tt_ids);
  x = x.add(tt_out);

  // Post-embedding normalization
  LayerHandle emb_norm(createLayer("layer_normalization", {
    withKey("name", "embedding_norm"),
    withKey("epsilon", NORM_EPS)
    , withKey("axis", 3)
  }));
  x = emb_norm(x);

  // Transformer encoder blocks
  for (int i = 0; i < NUM_LAYERS; ++i) {
    x = createTransformerDecoderBlock(i, x);
  }

  // Compile model from symbolic tensor graph.
  // Note: this symbolic overload also calls initialize() + allocate() internally.
  std::vector<Tensor> outputs = {x};
  int compile_status = model->compile(all_inputs, outputs, ml::train::ExecutionMode::INFERENCE);
  if (compile_status != 0) {
    throw std::invalid_argument(
      "BertModel::constructModel compile failed (status=" +
      std::to_string(compile_status) + ")");
  }
}

Tensor
BertModel::createTransformerDecoderBlock(const int layer_id,
                                      Tensor input) {

  using ml::train::createLayer;

  // Self attention
  Tensor att_out =
    createAttention(layer_id, INIT_SEQ_LEN, NUM_HEADS, HEAD_DIM,
                    input, input, input);

  // Attention residual + post-norm
  Tensor residual = input.add(att_out);
  LayerHandle att_norm(createLayer("layer_normalization", {
    withKey("name", "layer" + std::to_string(layer_id) + "_attention_norm"),
    withKey("epsilon", NORM_EPS)
    , withKey("axis", 3)
  }));
  Tensor normed = att_norm(residual);

  // Feed forward
  Tensor ffn_out = createMlp(layer_id, DIM, INTERMEDIATE_SIZE, normed);

  // FFN residual + post-norm
  Tensor ffn_residual = normed.add(ffn_out);
  LayerHandle ffn_norm(createLayer("layer_normalization", {
    withKey("name", "layer" + std::to_string(layer_id) + "_ffn_norm"),
    withKey("epsilon", NORM_EPS)
    , withKey("axis", 3)
  }));
  Tensor block_out = ffn_norm(ffn_residual);

  return block_out;
}

Tensor
BertModel::createAttention(const int layer_id, int seq_len,
                         int n_heads, int head_dim,
                         Tensor query, Tensor key,
                         Tensor value) {

  using ml::train::createLayer;

  auto V_name = "layer" + std::to_string(layer_id) + "_wv";
  auto K_name = "layer" + std::to_string(layer_id) + "_wk";
  auto Q_name = "layer" + std::to_string(layer_id) + "_wq";
  auto A_name = "layer" + std::to_string(layer_id) + "_attention";
  auto O_name = "layer" + std::to_string(layer_id) + "_attention_out";

  // V projection
  LayerHandle v_proj(createLayer("fully_connected", {
    withKey("name", V_name),
    withKey("unit", head_dim * n_heads / GQA_SIZE),
    withKey("disable_bias", "false")
  }));
  Tensor v = v_proj(value);

  // K projection
  LayerHandle k_proj(createLayer("fully_connected", {
    withKey("name", K_name),
    withKey("unit", head_dim * n_heads / GQA_SIZE),
    withKey("disable_bias", "false")
  }));
  Tensor k = k_proj(key);

  // Q projection
  LayerHandle q_proj(createLayer("fully_connected", {
    withKey("name", Q_name),
    withKey("unit", head_dim * n_heads),
    withKey("disable_bias", "false")
  }));
  Tensor q = q_proj(query);

  // Attention core layer
  std::vector<std::string> attn_props = {
    withKey("name", A_name),
    withKey("num_heads", n_heads),
    withKey("num_heads_kv", n_heads / GQA_SIZE),
    withKey("max_timestep", std::to_string(INIT_SEQ_LEN)),
    withKey("is_causal", IS_CAUSAL ? "true" : "false")
  };
  LayerHandle attn(createLayer("mha_core", attn_props));
  Tensor a = attn({q, k, v});

  // O projection
  LayerHandle o_proj(createLayer("fully_connected", {
    withKey("name", O_name),
    withKey("unit", DIM),
    withKey("disable_bias", "false")
  }));
  Tensor o = o_proj(a);

  return o;
}

void BertModel::registerCustomLayers() {
  Transformer::registerCustomLayers();
}

Tensor BertModel::createMlp(
  const int layer_id, int dim, int hidden_dim,
  Tensor input) {

  using ml::train::createLayer;

  LayerHandle ffn_fc1(createLayer("fully_connected", {withKey("name", "layer" + std::to_string(layer_id) + "_ffn_fc1"), withKey("unit", hidden_dim)}));
  Tensor ffn_fc1_out = ffn_fc1(input);

  LayerHandle ffn_act(createLayer("activation", {withKey("name", "layer" + std::to_string(layer_id) + "_ffn_act"), withKey("activation", "gelu")}));
  Tensor ffn_act_out = ffn_act(ffn_fc1_out);

  LayerHandle ffn_down(createLayer("fully_connected", {withKey("name", "layer" + std::to_string(layer_id) + "_ffn_down"), withKey("unit", dim)}));
  Tensor ffn_down_out = ffn_down(ffn_act_out);

  return ffn_down_out;
}

BertModel BertModel::createTestModel() {
  // Minimal JSON config for testing
  json cfg;
  cfg["vocab_size"] = 119547;
  cfg["hidden_size"] = 32;
  cfg["num_hidden_layers"] = 2;
  cfg["num_attention_heads"] = 4;
  cfg["num_key_value_heads"] = 4;
  cfg["head_dim"] = 8;
  cfg["intermediate_size"] = 128;
  cfg["layer_norm_eps"] = 1e-12;
  cfg["tie_word_embeddings"] = false;
  cfg["max_position_embeddings"] = 512;
  cfg["is_causal"] = false;

  json gen_cfg;
  gen_cfg["max_new_tokens"] = 0;

  json nntr_cfg;
  nntr_cfg["model_type"] = "embedding";
  nntr_cfg["init_seq_len"] = 8;
  nntr_cfg["max_seq_len"] = 8;
  nntr_cfg["num_to_generate"] = 0;
  nntr_cfg["batch_size"] = 1;
  nntr_cfg["model_tensor_type"] = "FP32-FP32";
  nntr_cfg["embedding_dtype"] = "FP32";
  nntr_cfg["fc_layer_dtype"] = "FP32";
  nntr_cfg["fsu"] = false;
  nntr_cfg["fsu_lookahead"] = 1;
  nntr_cfg["tokenizer_file"] = "";

  return BertModel(cfg, gen_cfg, nntr_cfg);
}

} // namespace causallm
