// Auto-generated by TorchFX-to-NNTrainer converter
// Model: lfm2 (decoder_only)
// Inherits from causallm::CausalLM

#ifndef __LFM2_700M_H__
#define __LFM2_700M_H__

#include "causal_lm.h"

namespace causallm {

/**
 * @brief Lfm2Transformer - model-specific attention variant
 * @note Overrides createAttention() for lfm2-specific behavior
 */
class Lfm2Transformer : virtual public Transformer {
public:
  Lfm2Transformer(json &cfg, json &generation_cfg, json &nntr_cfg)
    : Transformer(cfg, generation_cfg, nntr_cfg) {}

  Tensor createAttention(const int layer_id, int seq_len,
                         int n_heads, int head_dim,
                         Tensor query, Tensor key,
                         Tensor value) override;

  void registerCustomLayers() override;
};

/**
 * @brief Lfm2CausalLM Class
 * @note Auto-generated from HuggingFace lfm2 model
 */
class Lfm2CausalLM : public CausalLM, public Lfm2Transformer {

public:
  Lfm2CausalLM(json &cfg, json &generation_cfg, json &nntr_cfg)
    : Transformer(cfg, generation_cfg, nntr_cfg, ModelType::CAUSALLM),
      CausalLM(cfg, generation_cfg, nntr_cfg),
      Lfm2Transformer(cfg, generation_cfg, nntr_cfg) {}

  void constructModel() override;
  void setupParameters(json &cfg, json &generation_cfg,
                       json &nntr_cfg) override;
  Tensor createConvBlock(const int layer_id,
                         Tensor input);
  void registerCustomLayers() override;

  /**
   * @brief Test constructor with minimal config
   * @note Creates model with                                                        small dimensions for testing
   */
  static Lfm2CausalLM createTestModel();

  ModelHandle &getModel() { return model; }

public:
  unsigned int NUM_VOCAB;
  int DIM;
  int CONV_DIM;
  int CONV_DIM_OUT;
  int CONV_L_CACHE;
  bool CONV_BIAS;
};

} // namespace causallm

#endif // __LFM2_700M_H__
