// SPDX-License-Identifier: Apache-2.0
/**
 * Copyright (C) 2026 Samsung Electronics Co., Ltd. All Rights Reserved.
 *
 * @file   unittest_causallm_lfm2_moe_reference.cpp
 * @date   06 July 2026
 * @brief  Differential (cross-validation) tests for the LFM2-MoE CausalLM
 * model.
 *
 * Compares nntrainer's LFM2-MoE output against golden fixtures generated by a
 * pure-PyTorch reference (generate_lfm2_moe_reference.py). The generic checks
 * live in causallm_test_utils; this file only binds the LFM2-MoE adapter and
 * the fixture name. Tests skip automatically when fixtures are absent.
 *
 * Both FP32 and Q4_0 differential checks are provided. The router gate
 * weight has width num_experts (=4), not divisible by 32, but
 * Lfm2MoELayer::save already special-cases the gate and expert_bias weights
 * to DataType::NONE regardless of dtype, so they are never run through the
 * Q4_0 save path in the first place -- the width-divisibility rule that
 * blocks it for other layers (and unittest_causallm_qwen3_moe) does not
 * apply here.
 *
 * @see    https://github.com/nntrainer/nntrainer
 * @author Jungwon Lee <jungone.lee@samsung.com>
 * @bug    No known bugs except for NYI items
 */

#include <causallm_test_utils.h>

#include <gtest/gtest.h>

#include <lfm2_moe_causallm.h>

#include <memory>

namespace {

/**
 * @brief Differential model descriptor for the tiny LFM2-MoE fixture
 */
causallm_test::DifferentialModel lfm2MoeModel() {
  return {
    "lfm2_moe_tiny",
    [](causallm::json &cfg, causallm::json &gen_cfg, causallm::json &nntr_cfg) {
      return std::make_unique<
        causallm_test::CausalLMTestAdapter<causallm::Lfm2MoeCausalLM>>(
        cfg, gen_cfg, nntr_cfg);
    },
  };
}

/**
 * @brief FP32 prefill logits and greedy tokens match the reference
 */
TEST(Lfm2MoeDifferentialTest, FP32MatchesHFReference) {
  causallm_test::runFp32DifferentialChecks(lfm2MoeModel());
}

/**
 * @brief Q4_0 quantized logits stay within tolerance of the HF reference
 *
 * Stage E0 of docs/htp_attention/42_moe_ffn_quantize_and_wiring_task.md
 * (41_moe_ffn_e2e_and_perf_task.md sectionE0): this is the coverage gap
 * that section identified -- every prior tiny-model case was FP32-only,
 * so there was no Q4_0 check anywhere for LFM2-MoE.
 */
TEST(Lfm2MoeDifferentialTest, Q40MatchesHFReference) {
  causallm_test::runQ40DifferentialChecks(lfm2MoeModel());
}

} // namespace
