#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Writes a host stand-in for qaic's nntr_hvx.h from test/htp/nntr_hvx.idl.

qaic is a Hexagon SDK tool, so a host cannot generate the real header. This
one declares every method with the prototype qaic gives it -- remote_handle64
first, then each argument, a sequence as a pointer plus an int length, an
out scalar as a pointer -- so compiling the skel sources against it checks
their definitions against the IDL, which tools/htp_syntax_check.sh's
variadic stand-in cannot.
"""
import re
import sys

T = {"uint8": "uint8", "int8": "int8", "uint16": "uint16", "int16": "int16",
     "uint32": "uint32", "int32": "int32", "uint64": "uint64",
     "int64": "int64", "float": "float", "double": "double"}


def main(idl_path, out_path):
    idl = re.sub(r"//.*", "", open(idl_path).read())
    out = ["/* generated by gen_nntr_hvx_h.py -- host stand-in */",
           "#ifndef NNTR_HVX_H", "#define NNTR_HVX_H", "#include <remote.h>",
           "#include <AEEStdErr.h>",
           "int nntr_hvx_open(const char *uri, remote_handle64 *h);",
           "int nntr_hvx_close(remote_handle64 h);"]
    n = 0
    for name, args in re.findall(r"AEEResult\s+(\w+)\s*\((.*?)\)\s*;", idl,
                                 re.S):
        ps = ["remote_handle64 _h"]
        for a in (x.strip() for x in args.split(",") if x.strip()):
            m = re.match(r"(in|rout|inrout)\s+(sequence<(\w+)>|\w+)\s+(\w+)$",
                         a)
            if not m:
                sys.exit(f"gen_nntr_hvx_h.py: cannot read '{a}' in {name}")
            d, ty, seq, var = m.groups()
            if seq:
                ps += [("const " if d == "in" else "") + T[seq] + " *" + var,
                       "int " + var + "Len"]
            else:
                ps.append(T[ty] + (" " if d == "in" else " *") + var)
        out.append(f"int nntr_hvx_{name}({', '.join(ps)});")
        n += 1
    out.append("#endif")
    open(out_path, "w").write("\n".join(out) + "\n")
    if n == 0:
        sys.exit("gen_nntr_hvx_h.py: no methods found")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
